// mockUsuarios.ts
export interface Poem {
  id: number;
  title: string;
  author: string;
  content: string;
  date: string;
}

export const mockPoems: Poem[] = [
  {
    id: 1,
    title: "MENSAGEM POÉTICA EM HOMENAGEM A JOSÉ ANTONIO PELO SEU ANIVERSÁRIO NATALÍCIO NESTE DIA 17 DE DEZEMBRO DE 2016 PELO AVÔ E POETA SEVERINO CAVALCANTI DE ALBUQUERQUE.",
    author: "Severino Cavalcanti de Albuquerque",
    content: `
      COM BRILHO EXTRAORDINÁRIO
      DE ALEGRIA REPLETO,
      TRANSMITO O ANIVERSÁRIO
      DE JOSÉ ANTONIO MEU NETO,
      A FAMÍLIA REUNIDA
      NOS ESPLENDORES DA VIDA
      COM OS DONS BRILHANTES SEUS,
      VÃO PEDINDO NESTE INSTANTE
      PARA O ANIVERSARIANTE
      AS SANTAS BÊNÇÃOS DE DEUS.`,
    date: "2025-03-25 09:28:48"
  },
  {
    id: 2,
    title: "MENSAGEM POÉTICA EM HOMENAGEM A JOSÉ ANTONIO PELO SEU ANIVERSÁRIO NATALÍCIO NESTE DIA 17 DE DEZEMBRO DE 2016 PELO AVÔ E POETA SEVERINO CAVALCANTI DE ALBUQUERQUE.",
    author: "Severino Cavalcanti de Albuquerque",
    content: `
      COM BRILHO EXTRAORDINÁRIO
      DE ALEGRIA REPLETO,
      TRANSMITO O ANIVERSÁRIO
      DE JOSÉ ANTONIO MEU NETO,
      A FAMÍLIA REUNIDA
      NOS ESPLENDORES DA VIDA
      COM OS DONS BRILHANTES SEUS,
      VÃO PEDINDO NESTE INSTANTE
      PARA O ANIVERSARIANTE
      AS SANTAS BÊNÇÃOS DE DEUS.`,
    date: "2025-03-25 09:28:48"
  },
  {
    id: 3,
    title: "MENSAGEM POÉTICA EM HOMENAGEM A JOSÉ ANTONIO PELO SEU ANIVERSÁRIO NATALÍCIO NESTE DIA 17 DE DEZEMBRO DE 2016 PELO AVÔ E POETA SEVERINO CAVALCANTI DE ALBUQUERQUE.",
    author: "Severino Cavalcanti de Albuquerque",
    content: `
      COM BRILHO EXTRAORDINÁRIO
      DE ALEGRIA REPLETO,
      TRANSMITO O ANIVERSÁRIO
      DE JOSÉ ANTONIO MEU NETO,
      A FAMÍLIA REUNIDA
      NOS ESPLENDORES DA VIDA
      COM OS DONS BRILHANTES SEUS,
      VÃO PEDINDO NESTE INSTANTE
      PARA O ANIVERSARIANTE
      AS SANTAS BÊNÇÃOS DE DEUS.`,
    date: "2025-03-25 09:28:48"
  },
  {
    id: 4,
    title: "MENSAGEM POÉTICA EM HOMENAGEM A JOSÉ ANTONIO PELO SEU ANIVERSÁRIO NATALÍCIO NESTE DIA 17 DE DEZEMBRO DE 2016 PELO AVÔ E POETA SEVERINO CAVALCANTI DE ALBUQUERQUE.",
    author: "Severino Cavalcanti de Albuquerque",
    content: `
      COM BRILHO EXTRAORDINÁRIO
      DE ALEGRIA REPLETO,
      TRANSMITO O ANIVERSÁRIO
      DE JOSÉ ANTONIO MEU NETO,
      A FAMÍLIA REUNIDA
      NOS ESPLENDORES DA VIDA
      COM OS DONS BRILHANTES SEUS,
      VÃO PEDINDO NESTE INSTANTE
      PARA O ANIVERSARIANTE
      AS SANTAS BÊNÇÃOS DE DEUS.`,
    date: "2025-03-25 09:28:48"
  },
  {
    id: 5,
    title: "MENSAGEM POÉTICA EM HOMENAGEM A JOSÉ ANTONIO PELO SEU ANIVERSÁRIO NATALÍCIO NESTE DIA 17 DE DEZEMBRO DE 2016 PELO AVÔ E POETA SEVERINO CAVALCANTI DE ALBUQUERQUE.",
    author: "Severino Cavalcanti de Albuquerque",
    content: `
      COM BRILHO EXTRAORDINÁRIO
      DE ALEGRIA REPLETO,
      TRANSMITO O ANIVERSÁRIO
      DE JOSÉ ANTONIO MEU NETO,
      A FAMÍLIA REUNIDA
      NOS ESPLENDORES DA VIDA
      COM OS DONS BRILHANTES SEUS,
      VÃO PEDINDO NESTE INSTANTE
      PARA O ANIVERSARIANTE
      AS SANTAS BÊNÇÃOS DE DEUS.`,
    date: "2025-03-25 09:28:48"
  },
  {
    id: 6,
    title: "MENSAGEM POÉTICA EM HOMENAGEM A JOSÉ ANTONIO PELO SEU ANIVERSÁRIO NATALÍCIO NESTE DIA 17 DE DEZEMBRO DE 2016 PELO AVÔ E POETA SEVERINO CAVALCANTI DE ALBUQUERQUE.",
    author: "Severino Cavalcanti de Albuquerque",
    content: `
      COM BRILHO EXTRAORDINÁRIO
      DE ALEGRIA REPLETO,
      TRANSMITO O ANIVERSÁRIO
      DE JOSÉ ANTONIO MEU NETO,
      A FAMÍLIA REUNIDA
      NOS ESPLENDORES DA VIDA
      COM OS DONS BRILHANTES SEUS,
      VÃO PEDINDO NESTE INSTANTE
      PARA O ANIVERSARIANTE
      AS SANTAS BÊNÇÃOS DE DEUS.`,
    date: "2025-03-25 09:28:48"
  },
];
