spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/poems
spring.datasource.username=postgres
spring.datasource.password=password

api.security.token.secret=${JWT_SECRET:XT5vSQdxsKL0hfVgFCJ3JwZvtKv8yWWedYVfux1JWVE=}